- name: Install dependencies
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
    update_cache: true

- name: Get PostgreSQL repo key
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: "{{ key_location }}"
    checksum: sha256:0144068502a1eddd2a0280ede10ef607d1ec592ce819940991203941564e8e76

- name: Add PostgreSQL APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ key_location }}] https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: Install PostgreSQL & psycopg2 Python library
  ansible.builtin.apt:
    name:
      - "postgresql-{{ pg_version }}"
      - python3-psycopg2
    update_cache: true

- name: Start and enable PostgreSQL
  ansible.builtin.systemd:
    state: started
    name: postgresql
    enabled: true

- name: Add DBUSER
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user_name }}"
    password: "{{ db_user_password }}"
  tags: createuser

- name: Add DB
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user_name }}"
  tags: createdb

- name: Permit DBUSER to DB
  community.postgresql.postgresql_pg_hba:
    dest: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    contype: host
    databases: "{{ db_name }}"
    users: "{{ db_user_name }}"
    address: "all"
    method: "md5"
  tags:
    - createdb
    - createuser
  notify:
    - Restart PostgreSQL

- name: Flush handlers
  meta: flush_handlers

- name: Grant permissions to DBUSER
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
    database: "{{ db_name }}"
    roles: "{{ db_user_name }}"
    privs: ALL
    type: database
  tags:
    - createdb
    - createuser