- name: Install PostgreSQL
  ansible.builtin.apt:
    name: postgresql
    update_cache: true

- name: Install PostgreSQL python module
  ansible.builtin.pip:
    name: psycopg2-binary

- name: Start and enable PostgreSQL
  ansible.builtin.systemd:
    state: started
    name: postgresql
    enabled: true

- name: Add DBUSER
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user_name }}"
    password: "{{ db_user_password }}"
  tags: createuser

- name: Add DB
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
  tags: createdb

- name: Permit DBUSER to DB
  community.postgresql.postgresql_pg_hba:
    dest: "/etc/postgresql/14/main/pg_hba.conf"
    contype: host
    databases: "{{ db_name }}"
    users: "{{ db_user_name }}"
    address: "all"
    method: "md5"
  tags:
    - createdb
    - createuser
  notify:
    - Restart PostgreSQL

- name: Flush handlers
  meta: flush_handlers

- name: Grant permissions to DBUSER
  community.postgresql.postgresql_privs:
    database: "{{ db_name }}"
    roles: "{{ db_user_name }}"
    privs: ALL
    type: database
  tags:
    - createdb
    - createuser