- hosts: localhost
  connection: local
  vars:
    cloudflare_token: !vault |
                      $ANSIBLE_VAULT;1.1;AES256
                      39646663306231353230356261623961663137383833646236393936376330646663313962353731
                      3935653331383764316136626633343938343064353330610a333037343431316165353962336631
                      61623736616430383636336636616139353338323233623465383830613439383762343831393938
                      6166636630303365620a653333336263666437306261323331373863333738623834303861373262
                      32386261343632306431313437663163383133336333626132373535376561626565383031343539
                      6233363264653462626637396535323233393161613730346636
  become: true

  tasks:
  #- name: Dump All Facts
  #  ansible.builtin.debug:
  #    var: hostvars[inventory_hostname]
  - name: Install basic packages
    ansible.builtin.apt:
      name:
        - htop
        - iotop
        - iftop
        - byobu
        - vim
        - neofetch
        - python3
        - unzip
        - locate
      update_cache: true
  #- name: Print Serial Number
  #  ansible.builtin.debug:
  #    msg: "SN: {{ ansible_product_serial }}"
  - name: Set Hostname
    ansible.builtin.hostname:
      name: "{{ ansible_product_serial | lower }}"
  #- name: Print Default v4
  #  ansible.builtin.debug:
  #    msg: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
  - name: Configure NOPASSWD for non-root user
    community.general.sudoers:
      name: "xoh-nopasswd"
      user: "xoh"
      commands: "ALL"
      nopassword: true
  - name: Create xoh.systems A record
    community.general.cloudflare_dns:
      zone: xoh.systems
      record: "{{ ansible_product_serial | lower }}"
      type: A
      value: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
      api_token: "{{ cloudflare_token }}"
      state: present
  #- name: Add system to xoh.systems inventory
  #  community.general.cloudflare_dns:
  #    zone: xoh.systems
  #    record: "inventory"
  #    type: TXT
  #    value: "{{ ansible_product_serial | lower }}"
  #    api_token: "{{ cloudflare_token }}"
  #    state: present
