- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Print Serial Number
    debug:
      msg: "SN: {{ ansible_product_serial }}"
  - name: Set Hostname
    hostname:
      name: "{{ ansible_product_serial | lower }}"
