- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Print Serial Number
    debug:
      msg: "SN: {{ ansible_product_serial }}"
  - name: Set Hostname
    hostname:
      name: "{{ ansible_product_serial | lower }}"
  #- name: Dump Facts
  #  debug:
  #    var: hostvars[inventory_hostname]
  - name: Print Default v4
    debug:
      msg: "{{ ansible_default_ipv4.address }}
