- name: Create vault group
  ansible.builtin.group:
    name: vault
    state: present

- name: Create vault user
  ansible.builtin.user:
    name: vault
    group: vault
    state: present

- name: Create vault config directory
  ansible.builtin.file:
    path: "{{ vault_config_directory }}"
    mode: '0770'
    owner: vault
    group: vault
    state: directory

- name: Create vault data directory
  ansible.builtin.file:
    path: "{{ vault_data_directory }}"
    mode: '0770'
    owner: vault
    group: vault
    state: directory

- name: Add vault config file
  ansible.builtin.template:
    src: "config.hcl.j2"
    dest: "{{ vault_config_directory }}/vault.hcl"
    owner: vault
    group: vault
    mode: '0660'

- name: Add vault systemd service file
  ansible.builtin.template:
    src: "vault.service.j2"
    dest: "/lib/systemd/system/vault.service"
    mode: '0644'