- name: Install Vault
  ansible.builtin.include_tasks:
    file: install.yml

- name: Configure Vault
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Activate and start vault service
  ansible.builtin.systemd_service:
    name: vault
    daemon_reload: true
    enabled: true
    state: started

- name: Initialize Vault
  ansible.builtin.include_tasks:
    file: initialize.yml
  tags:
    - never
    - init_vault