maas_version: "3.5"
db_user_name: "maas"
db_name: "maas"
upstream_dns: "8.8.8.8 8.8.4.4"
maas_name: "maas"
maas_images:
  - { os: ubuntu, release: "jammy", arches: "amd64", subarches: "*", labels: "*" }
  - { os: ubuntu, release: "noble", arches: "amd64", subarches: "*", labels: "*" }
maas_url: "http://{{ maas_domain }}:5240/MAAS"