maas_version: "3.5"
db_user_name: "maas"
db_name: "maas"
upstream_dns: "8.8.8.8 8.8.4.4"
maas_name: "maas"
maas_images:
  - { os: ubuntu, release: "jammy", arches: "amd64", subarches: "*", labels: "*" }
  - { os: ubuntu, release: "noble", arches: "amd64", subarches: "*", labels: "*" }
enable_disk_erasing_on_release: "true"
disk_erase_with_secure_erase: "false"
disk_erase_with_quick_erase: "true"
maas_url: "http://{{ maas_domain }}:5240/MAAS"
maas_dns_domain: "{{ maas_domain }}"
maas_deploy_default: noble
maas_commission_default: noble