- hosts: 8cc0512f9l
  become: true
  gather_facts: true
  roles:
    - role: postgresql
      vars:
        db_user_name: "maas"
        db_user_password: "{{ secrets.maas_postgresql_pguser }}"
        db_name: "maas"
    - role: maas
      vars:
        db_user_password: "{{ secrets.maas_postgresql_pguser }}"
        maas_admin_name: "xoh"
        maas_admin_password: "{{ secrets.maas_admin }}"
        maas_admin_mail: "xoh@xoh.dev"
        maas_admin_key: "gh:xoh"
  vars_files:
    - "{{ bootstrap_vault }}"