- hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: postgresql
      vars:
        db_user_name: "maas"
        db_user_password: "{{ secrets.maas_postgresql_pguser }}"
        db_name: "maas"
    - role: terraform
    - role: maas
      vars:
        db_user_password: "{{ secrets.maas_postgresql_pguser }}"
        maas_admin_name: "xoh"
        maas_admin_password: "{{ secrets.maas_admin }}"
        maas_admin_mail: "xoh@xoh.dev"
        maas_admin_key: "gh:xoh"
        maas_name: "lls21"
        maas_domain: "maas.xoh.systems"
        maas_dns_domain: "xoh.systems"
        configure_unifi_dhcp: true
        unifi_url: "https://172.16.6.254/"
        unifi_user: "{{ secrets.unifi_terraform_user }}"
        unifi_pass: "{{ secrets.unifi_terraform_pass }}"
    - role: orchestrator
      vars:
        orchestrator_homedir: "/home/xoh"
  vars_files:
    - "{{ bootstrap_vault }}"