- name: Add MAAS repository from PPA
  ansible.builtin.apt_repository:
    repo: "ppa:maas/{{ maas_version }}"

- name: Uninstall conflicting systemd-timesyncd
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: absent

- name: Install MAAS
  ansible.builtin.apt:
    name: maas
    update_cache: true