- name: Create MAAS CNAME record
  community.general.cloudflare_dns:
    zone: xoh.systems
    record: "{{ maas_domain }}"
    type: CNAME
    value: "{{ ansible_product_serial | lower }}.xoh.systems"
    api_token: "{{ secrets.cloudflare_token_dns_xoh_systems }}"
    state: present

- name: Install MAAS
  ansible.builtin.include_tasks:
    file: install.yml

- name: Initialize MAAS
  ansible.builtin.include_tasks:
    file: initialize.yml

- name: Configure MAAS
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Extended configuration utilizing terraform
  ansible.builtin.include_tasks:
    file: terraform.yml

- name: Continue MAAS setup
  debug:
    msg: "Continue to {{ maas_url }} to finish the installation"